# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 9, 3, 17, 12, 57, 621422, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='static/img')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 9, 3, 17, 12, 57, 589688, tzinfo=utc), verbose_name='date published')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
    ]
