# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170907_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
