# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='', upload_to='app/static/img'),
        ),
    ]
