# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170909_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='app/img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_post_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=[], size=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='', upload_to='app/img/'),
        ),
    ]
