# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170911_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_post_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, unique=True), blank=True, default=[], size=50),
        ),
    ]
