# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 21:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170911_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, unique=True), blank=True, default=[], size=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, unique=True), blank=True, default=[], size=500),
        ),
    ]
